config/routes.rb
Rails.application.routes.draw do

  post :article_comment, controller: :landing, action: :article_comment
  root controller: :landing, action: :index

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @articles = Article.all
  end

  def article_comment
    #binding.pry
    article = Article.find(params[:article])
    article.comments.create(comment: params[:comment])
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing/index.html.erb
<ul>
  <% @articles.each do |article| %>
    <li>
      <%= article.title %><br/>
      <%= article.content %>
      <%= "Written by #{article.author} at #{article.created_at.strftime('%F')}" %>

    </li>
    <li>
      <%= form_tag article_comment_path, id: "article_#{article.id}" do %>
        <%= hidden_field_tag :article, article.id %>
        <%= label_tag :comment %>
        <%= text_field_tag :comment %>
        <%= submit_tag 'Submit' %>
      <% end %>
    </li>
    <% if article.comments  %>
      <ul>
        <% article.comments.each do |comment| %>
          <li>
            <%= comment.comment %>
          </li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDemoNov</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>